#!/bin/bash
# Skrip untuk mengelola VM berbasis QEMU untuk Alpine Linux (aarch64)

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
VM_NAME="${SCRIPT_NAME%.sh}"
ISO_URL="https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/aarch64/\
alpine-virt-3.21.0-aarch64.iso"
RESOURCES_DIR="${SCRIPT_DIR}/resources"
VM_DISK="${RESOURCES_DIR}/${VM_NAME}.vdi"
VM_FIRMWARE="${RESOURCES_DIR}/${VM_NAME}.fd"
SHARED_DIR="${SCRIPT_DIR}/shared"
FIRMWARE_CODE="${RESOURCES_DIR}/edk2-aarch64-code.fd"
ISO_PATH="${RESOURCES_DIR}/$(basename $ISO_URL)"

# Fungsi untuk membuat disk virtual
create_disk() {
    qemu-img create -f vdi "$1" 2G
}

# Fungsi untuk mengunduh file ISO
download_iso() {
    local url="$1"
    local output="$2"
    if ! curl -# -L "$url" -o "$output" --fail; then
        echo "Error: Gagal mengunduh ISO dari $url" >&2
        exit 1
    fi
}

# Fungsi untuk membersihkan sumber daya
clean() {
    echo "Membersihkan sumber daya..."
    rm -f "$VM_DISK"
    rm -f "$VM_FIRMWARE"
    echo "Pembersihan selesai."
}

# Fungsi untuk menjalankan VM
run_vm() {
    local accel=""
    if [ "$(uname)" = "Darwin" ]; then
        accel="-accel hvf -cpu host"
    fi

    clear
    sudo qemu-system-aarch64 \
        -name "$VM_NAME" \
        -machine virt \
        -smp 2 \
        -m 1G \
        -drive if=pflash,format=raw,file="$FIRMWARE_CODE",readonly=on \
        -drive if=pflash,format=raw,file="$VM_FIRMWARE" \
        -drive "file=$VM_DISK,format=vdi,if=virtio" \
        -nic user \
        -nic vmnet-bridged,ifname=en0 \
        -device virtio-gpu-pci \
        -device qemu-xhci \
        -device usb-kbd \
        -device usb-tablet \
        -device virtio-sound,streams=1 $accel "$@"
}

# Fungsi untuk menginstal VM menggunakan ISO
install() {
    mkdir -p "$RESOURCES_DIR"

    # Buat disk virtual jika belum ada
    if [ ! -f "$VM_DISK" ]; then
        create_disk "$VM_DISK"
    fi

    # Salin firmware jika belum ada
    if [ ! -f "$VM_FIRMWARE" ]; then
        cp "$FIRMWARE_CODE" "$VM_FIRMWARE"
    fi

    # Download iso file jika belum ada
    if [ ! -f "$ISO_PATH" ]; then
        download_iso "$ISO_URL" "$ISO_PATH"
    fi

    run_vm -cdrom "$ISO_PATH" "$@"
}

# Fungsi utama
main() {
    # Pilih aksi berdasarkan argumen pertama
    case "$1" in
        clean)
            clean
            ;;
        install)
            install "${@:2}"
            ;;
        *)
            run_vm "$@"
            ;;
    esac
}

main "$@"
